### ISSUE TITLE
Map Display Issue

### ISSUE THREAD

**Issue by KayleeWells** [pkmnct/qualtrics-google-map-lat-long#16]
I'm having an issue where the map displays if I preview the question individually but only the search bar displays when viewing the question in the survey in preview mode.

Is there a way to fix this?

**Comment by pkmnct** [comment]
@KayleeWells Can you recreate the issue and then attach the console logs from that page? Here's instructions for copying the logs: https://support.google.com/docs/thread/1873663?hl=en

**Comment by KayleeWells** [comment]
@pkmnct Here is the console log:
This site overrides Array.from() with an implementation that doesn't support iterables, which could cause Google Maps JavaScript API v3 to not work correctly.
Hj @ js?libraries=places&key=
js?libraries=places&key= 
This site overrides Array.from() with an implementation that doesn't support iterables, which could cause Google Maps JavaScript API v3 to not work correctly.
Hj @ js?libraries=places&key=
js?libraries=places&key= 
This site overrides Array.from() with an implementation that doesn't support iterables, which could cause Google Maps JavaScript API v3 to not work correctly.
Hj @ js?libraries=places&key=
js?libraries=places&key=
You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.
Ij @ js?libraries=places&key=
js?libraries=places&key= 
This site overrides Array.from() with an implementation that doesn't support iterables, which could cause Google Maps JavaScript API v3 to not work correctly.
Hj @ js?libraries=places&key=
js?libraries=places&key= 
You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.
Ij @ js?libraries=places&key=
js?libraries=places&key=
 Uncaught (in promise) TypeError: Cannot read property 'j' of undefined
    at js?libraries=places&key=
js?libraries=places&key=
 Uncaught (in promise) TypeError: Cannot read property 'j' of undefined
    at js?libraries=places&key=

Thanks for taking a look!

**Comment by KayleeWells** [comment]
I solved the problem. I was trying to loop & merge the map question and once I turned off the loop & merge I could see the map in full preview mode.
