### ISSUE TITLE
Array.from() conflict with Qualtrics

### ISSUE THREAD

**Issue by razvann** [pkmnct/qualtrics-google-map-lat-long#17]
This site overrides Array.from() with an implementation that doesn't support iterables, which could cause Google Maps JavaScript API v3 to not work correctly.

**Comment by pkmnct** [comment]
Yes, this is a warning from the Google Maps API due to Qualtrics having a custom `Array.from()` implementation. It doesn't seem to affect functionality, besides showing the warning.
