### ISSUE TITLE
Piping in location

### ISSUE THREAD

**Issue by dsikkink** [pkmnct/qualtrics-google-map-lat-long#2]
Thanks for this very useful code. Nicely done. 

Question: how would I pipe in a text response from a previous Qualtrics question as a parameter for the location shown in the initial map? For example, in an earlier question, I ask respondents to provide their city (or zip code). I would like to use that city name provided by the respondent as input for the autocomplete box in your java script (as a place for the respondent to start on the Google map). Then I can ask the respondent to drop the pin in a more specific place within their city.  

Thanks.

**Comment by pkmnct** [comment]
While I can see this being useful, more advanced usage of the Qualtrics API is outside the scope of this project. [Here is a similar use case on Qualtrics](https://www.qualtrics.com/community/discussion/682/how-do-i-use-a-part-of-the-answer-of-a-previous-question-as-an-answer-in-a-following-question) that may be of help. I am closing this issue for now.
