### ISSUE TITLE
the red pin doesn't follow

### ISSUE THREAD

**Issue by dsikkink** [pkmnct/qualtrics-google-map-lat-long#3]
I think I am seeing this right...if you grab and pull the map, the red pin doesn't "follow" you to the new map location. So you have to zoom out, find the pin, and drag it into the right map area. 

However, if you enter a city or other location info in the text box and select a location, the pin will "jump" with you to the new map area. 

Would be much more convenient for the respondent if the red pin would follow them around. 

Thanks.

**Comment by pkmnct** [comment]
With version 2.0, you can now click on the map to set the marker location if you only have one marker. I feel that this is more clear to a user that has used Google Maps than having the pin scroll with you.
