### ISSUE TITLE
How to store lat and lon separately?

### ISSUE THREAD

**Issue by infiniteugi** [pkmnct/qualtrics-google-map-lat-long#5]
Is there a method to store lat and lon separately as Qualtrics embedded data?

**Comment by Louocean** [comment]
I am having trouble finding the lat/long in the qualtrics data output. Did you work out how to find it?

**Comment by elijanet** [comment]
> I am having trouble finding the lat/long in the qualtrics data output. Did you work out how to find it?

This took me hours to figure out and it was so simple! You need to make sure the **Text Type** in Qualtrics is set as **Single Line** and not **Form**. It then records the lat/long in Data & Analysis.

**Comment by pkmnct** [comment]
@infiniteugi Due to the way the data is passed from Google Maps to the Qualtrics Survey, it is not currently possible to store the lat and long separately.
