### ISSUE TITLE
lat/lon from google maps not stored

### ISSUE THREAD

**Issue by debsuconn** [pkmnct/qualtrics-google-map-lat-long#6]
Hi,
I have developed a survey to collect locations of healthcare facilities by using the qualtrics-google code. While I am conducting a survey, everything work such as search box, red pin etc but the lat and lon data and the name of the location are not saved in the database. Any solution to solve this issue? 

Thanks.

**Comment by Louocean** [comment]
I also have the same problem... were you able to find the data?

**Comment by forestbarnes** [comment]
Any solution to this problem? I'm having the same issue

**Comment by pkmnct** [comment]
The result should be collected in the Qualtrics question field as a string representation of a JSON object. It will be in the format as follows:

`{"lat": "38.8951", "long": "-77.0364"}`

**Comment by elijanet** [comment]
This took me hours to figure out and it was so simple! You need to make sure the **Text Type** in Qualtrics is set as **Single Line** and not **Form**. It then records the lat/long in Data & Analysis.

Perhaps the author can specify the above in the instructions?

**Comment by pkmnct** [comment]
@elijanet Thank you for this, I had not been successful in recreating the reported bug. @forestbarnes @Louocean @debsuconn If any of you are still having this issue, let me know if @elijanet's solution works for you.

**Comment by forestbarnes** [comment]
This fix worked for me! PLEASE specify this in the instructions - it would have saved me quite a bit of time and hassle. Thank you!!

**Comment by pkmnct** [comment]
I have included this in the documentation setup and troubleshooting sections. If anyone continues to face this issue after following this workaround, please feel free to re-open this issue.
