### ISSUE TITLE
Zoom limit

### ISSUE THREAD

**Issue by cnaptik** [pkmnct/qualtrics-google-map-lat-long#9]
Would it be possible to limit the zoom level of the plugin?

In my application scenario, when picking a location on the map, I would like the user to be restricted by how much it is possible to zoom in, so that the picked location remains approximate (country/region level, not a specific city or address).

**Comment by pkmnct** [comment]
Version 2.0 has been released, which exposes all Google Maps options. This means you can easily set the [maxZoom option](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions).
